backend:
  name: github
  repo: wangxin-oss/wangxin-oss.github.io
  branch: main
collections:
  - name: "test"
    label: "测试"
    folder: "test"
    create: true
    fields:
      - {label: "标题", name: "title", widget: "string"}
