backend:
  name: netlify  # 注意冒号后必须有空格
  branch: main   # 与 Netlify 部署分支一致（main 或 master）

# 其他配置（媒体文件夹、集合等）
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "博客文章"
    folder: "_posts"
    create: true
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "内容", name: "body", widget: "markdown"}
