backend:
  name: github
  repo: wangxin-oss/wangxin-oss.github.io 
  branch: main  
collections:
  - name: "posts"
    label: "日志"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "内容", name: "body", widget: "markdown"}
